### ISSUE TITLE
Match number enums

### ISSUE THREAD

**Issue by Spaubleit** [housinganywhere/match#7]
Match number enums not working. I get error: Error:(8, 17) TS2344: Type 'ObjectStatus' does not satisfy the constraint 'string'.

Example:
```typescript
export enum ObjectStatus {
    OPENED = 10,
    CLOSED = 20,
}

const x = match<ObjectStatus, string>({
});
```

**Comment by gillchristian** [comment]
Hello @Spaubleit 

Sorry that I just see your message. It should be a small change to extend the support to numeric enums. Feel free to open a PR.
